const labelTweaks = [
  {label : "AL"},
  {label : "AK"},
  {label : "AR"},
  {label : "AZ"},
  {label : "CA"},
  {label : "CO"},
  {label : "CT", tweaks: [3, 20]},
  {label : "DE", tweaks: [20, 10]},
  {label : "FL", tweaks: [15, 0]},
  {label : "GA"},
  {label : "HI", tweaks: [8, 5]},
  {label : "ID"},
  {label : "IL"},
  {label : "IN"},
  {label : "IA"},
  {label : "KS"},
  {label : "KY"},
  {label : "LA", tweaks: [-10, 0]},
  {label : "ME"},
  {label : "MD"},
  {label : "MA", tweaks: [40, -5]},
  {label : "MI", tweaks: [15, 30]},
  {label : "MN"},
  {label : "MS"},
  {label : "MO"},
  {label : "MT"},
  {label : "MT"},
  {label : "NE"},
  {label : "NV"},
  {label : "NH", tweaks: [-3, 10]},
  {label : "NJ", tweaks: [25, 10]},
  {label : "NM"},
  {label : "NY"},
  {label : "NC"},
  {label : "ND"},
  {label : "OH"},
  {label : "OK"},
  {label : "OR"},
  {label : "PA"},
  {label : "RI", tweaks: [8, 17]},
  {label : "SC"},
  {label : "SD"},
  {label : "TN"},
  {label : "TX"},
  {label : "UT"},
  {label : "VT", tweaks: [-5, 0]},
  {label : "VA"},
  {label : "WA"},
  {label : "WV", tweaks: [-5, 0]},
  {label : "WI"},
  {label : "WY"},
]

function matchLabelToTweak(state) {
  const index = labelTweaks.findIndex(st => st.label === state.properties.STATE_ABBR)
  return (labelTweaks[index].tweaks) ? labelTweaks[index].tweaks : null
}

export { labelTweaks, matchLabelToTweak }